//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infecon.CSSD.Monitor.SmartNode.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infecon.CSSD.Monitor.SmartNode.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 湿度 的本地化字符串。
        /// </summary>
        internal static string HumiditySeries {
            get {
                return ResourceManager.GetString("HumiditySeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        internal static string HumidityUnit {
            get {
                return ResourceManager.GetString("HumidityUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气压 的本地化字符串。
        /// </summary>
        internal static string PressureSeries {
            get {
                return ResourceManager.GetString("PressureSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bar 的本地化字符串。
        /// </summary>
        internal static string PressureUnit {
            get {
                return ResourceManager.GetString("PressureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度 的本地化字符串。
        /// </summary>
        internal static string TemperatureSeries {
            get {
                return ResourceManager.GetString("TemperatureSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 °C 的本地化字符串。
        /// </summary>
        internal static string TemperatureUnit {
            get {
                return ResourceManager.GetString("TemperatureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        internal static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压 的本地化字符串。
        /// </summary>
        internal static string VoltageSeries {
            get {
                return ResourceManager.GetString("VoltageSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V 的本地化字符串。
        /// </summary>
        internal static string VoltageUnit {
            get {
                return ResourceManager.GetString("VoltageUnit", resourceCulture);
            }
        }
    }
}
