//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infecon.CSSD.Monitor.Belimed.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infecon.CSSD.Monitor.Belimed.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 5000 的本地化字符串。
        /// </summary>
        internal static string A0MaxValue {
            get {
                return ResourceManager.GetString("A0MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string A0MinValue {
            get {
                return ResourceManager.GetString("A0MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FValue1 的本地化字符串。
        /// </summary>
        internal static string CheckedField {
            get {
                return ResourceManager.GetString("CheckedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ElapsedTime 的本地化字符串。
        /// </summary>
        internal static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3500 的本地化字符串。
        /// </summary>
        internal static string PressureMaxValue {
            get {
                return ResourceManager.GetString("PressureMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string PressureMinValue {
            get {
                return ResourceManager.GetString("PressureMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mbar a 的本地化字符串。
        /// </summary>
        internal static string PressureUnit {
            get {
                return ResourceManager.GetString("PressureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序名称 的本地化字符串。
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序名称标题 的本地化字符串。
        /// </summary>
        internal static string ProgramNameCaption {
            get {
                return ResourceManager.GetString("ProgramNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序编号 的本地化字符串。
        /// </summary>
        internal static string ProgramNo {
            get {
                return ResourceManager.GetString("ProgramNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序阶段 的本地化字符串。
        /// </summary>
        internal static string ProgramPhase {
            get {
                return ResourceManager.GetString("ProgramPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T1 的本地化字符串。
        /// </summary>
        internal static string SterilizerSeries1 {
            get {
                return ResourceManager.GetString("SterilizerSeries1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度 的本地化字符串。
        /// </summary>
        internal static string SterilizerSeries2 {
            get {
                return ResourceManager.GetString("SterilizerSeries2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P1 的本地化字符串。
        /// </summary>
        internal static string SterilizerSeries3 {
            get {
                return ResourceManager.GetString("SterilizerSeries3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力 的本地化字符串。
        /// </summary>
        internal static string SterilizerSeries4 {
            get {
                return ResourceManager.GetString("SterilizerSeries4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P3 的本地化字符串。
        /// </summary>
        internal static string SterilizerSeries5 {
            get {
                return ResourceManager.GetString("SterilizerSeries5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P4 的本地化字符串。
        /// </summary>
        internal static string SterilizerSeries6 {
            get {
                return ResourceManager.GetString("SterilizerSeries6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template\BelimedSterilizerStatus.html 的本地化字符串。
        /// </summary>
        internal static string SterilizerStatusTemplatePath {
            get {
                return ResourceManager.GetString("SterilizerStatusTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 140 的本地化字符串。
        /// </summary>
        internal static string TempMaxValue {
            get {
                return ResourceManager.GetString("TempMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string TempMinValue {
            get {
                return ResourceManager.GetString("TempMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 °C 的本地化字符串。
        /// </summary>
        internal static string TempUnit {
            get {
                return ResourceManager.GetString("TempUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UpdatedTime 的本地化字符串。
        /// </summary>
        internal static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Med 的本地化字符串。
        /// </summary>
        internal static string WasherSeries1 {
            get {
                return ResourceManager.GetString("WasherSeries1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度 的本地化字符串。
        /// </summary>
        internal static string WasherSeries2 {
            get {
                return ResourceManager.GetString("WasherSeries2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CDNo 的本地化字符串。
        /// </summary>
        internal static string WasherSeries3 {
            get {
                return ResourceManager.GetString("WasherSeries3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DosV 的本地化字符串。
        /// </summary>
        internal static string WasherSeries4 {
            get {
                return ResourceManager.GetString("WasherSeries4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A0 的本地化字符串。
        /// </summary>
        internal static string WasherSeries5 {
            get {
                return ResourceManager.GetString("WasherSeries5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template\BelimedWasherStatus.html 的本地化字符串。
        /// </summary>
        internal static string WasherStatusTemplatePath {
            get {
                return ResourceManager.GetString("WasherStatusTemplatePath", resourceCulture);
            }
        }
    }
}
