#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="InfeconHNSRM")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TestLINQ.Properties.Settings.Default.InfeconHNSRMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MonitorCollectData> MonitorCollectData
		{
			get
			{
				return this.GetTable<MonitorCollectData>();
			}
		}
		
		public System.Data.Linq.Table<MonitorCollectDataEntry> MonitorCollectDataEntry
		{
			get
			{
				return this.GetTable<MonitorCollectDataEntry>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonitorCollectData")]
	public partial class MonitorCollectData
	{
		
		private int _FID;
		
		private System.Nullable<System.Guid> _FLogID;
		
		private string _FDeviceID;
		
		private int _FMonitorType;
		
		private int _FDataSourceType;
		
		private System.Nullable<System.DateTime> _FBeginDate;
		
		private System.Nullable<System.DateTime> _FEndDate;
		
		private System.Nullable<int> _FSystemNo;
		
		private System.Nullable<int> _FVersion;
		
		private System.Nullable<int> _FProgramNo;
		
		private string _FPargramName;
		
		private string _FProgramPhrase;
		
		private System.Nullable<int> _FBatchNo;
		
		private System.Nullable<int> _FZoneNo;
		
		private int _FHasCompress;
		
		public MonitorCollectData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FID", DbType="Int NOT NULL")]
		public int FID
		{
			get
			{
				return this._FID;
			}
			set
			{
				if ((this._FID != value))
				{
					this._FID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLogID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> FLogID
		{
			get
			{
				return this._FLogID;
			}
			set
			{
				if ((this._FLogID != value))
				{
					this._FLogID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDeviceID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string FDeviceID
		{
			get
			{
				return this._FDeviceID;
			}
			set
			{
				if ((this._FDeviceID != value))
				{
					this._FDeviceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FMonitorType", DbType="Int NOT NULL")]
		public int FMonitorType
		{
			get
			{
				return this._FMonitorType;
			}
			set
			{
				if ((this._FMonitorType != value))
				{
					this._FMonitorType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDataSourceType", DbType="Int NOT NULL")]
		public int FDataSourceType
		{
			get
			{
				return this._FDataSourceType;
			}
			set
			{
				if ((this._FDataSourceType != value))
				{
					this._FDataSourceType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FBeginDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FBeginDate
		{
			get
			{
				return this._FBeginDate;
			}
			set
			{
				if ((this._FBeginDate != value))
				{
					this._FBeginDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> FEndDate
		{
			get
			{
				return this._FEndDate;
			}
			set
			{
				if ((this._FEndDate != value))
				{
					this._FEndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FSystemNo", DbType="Int")]
		public System.Nullable<int> FSystemNo
		{
			get
			{
				return this._FSystemNo;
			}
			set
			{
				if ((this._FSystemNo != value))
				{
					this._FSystemNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FVersion", DbType="Int")]
		public System.Nullable<int> FVersion
		{
			get
			{
				return this._FVersion;
			}
			set
			{
				if ((this._FVersion != value))
				{
					this._FVersion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FProgramNo", DbType="Int")]
		public System.Nullable<int> FProgramNo
		{
			get
			{
				return this._FProgramNo;
			}
			set
			{
				if ((this._FProgramNo != value))
				{
					this._FProgramNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPargramName", DbType="VarChar(50)")]
		public string FPargramName
		{
			get
			{
				return this._FPargramName;
			}
			set
			{
				if ((this._FPargramName != value))
				{
					this._FPargramName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FProgramPhrase", DbType="VarChar(50)")]
		public string FProgramPhrase
		{
			get
			{
				return this._FProgramPhrase;
			}
			set
			{
				if ((this._FProgramPhrase != value))
				{
					this._FProgramPhrase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FBatchNo", DbType="Int")]
		public System.Nullable<int> FBatchNo
		{
			get
			{
				return this._FBatchNo;
			}
			set
			{
				if ((this._FBatchNo != value))
				{
					this._FBatchNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FZoneNo", DbType="Int")]
		public System.Nullable<int> FZoneNo
		{
			get
			{
				return this._FZoneNo;
			}
			set
			{
				if ((this._FZoneNo != value))
				{
					this._FZoneNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FHasCompress", DbType="Int NOT NULL")]
		public int FHasCompress
		{
			get
			{
				return this._FHasCompress;
			}
			set
			{
				if ((this._FHasCompress != value))
				{
					this._FHasCompress = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonitorCollectDataEntry")]
	public partial class MonitorCollectDataEntry
	{
		
		private int _FParentID;
		
		private System.DateTime _FDate;
		
		private System.Nullable<decimal> _FValue1;
		
		private System.Nullable<decimal> _FValue2;
		
		private System.Nullable<decimal> _FValue3;
		
		private string _FReceiveString;
		
		private int _FID;
		
		private string _FCurrentStatus;
		
		private string _FProgramPhrase;
		
		private System.Nullable<int> _FErrorNo;
		
		private System.Nullable<decimal> _FValue4;
		
		private System.Nullable<decimal> _FValue5;
		
		private System.Nullable<decimal> _FValue6;
		
		public MonitorCollectDataEntry()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FParentID", DbType="Int NOT NULL")]
		public int FParentID
		{
			get
			{
				return this._FParentID;
			}
			set
			{
				if ((this._FParentID != value))
				{
					this._FParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDate", DbType="DateTime NOT NULL")]
		public System.DateTime FDate
		{
			get
			{
				return this._FDate;
			}
			set
			{
				if ((this._FDate != value))
				{
					this._FDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FValue1", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FValue1
		{
			get
			{
				return this._FValue1;
			}
			set
			{
				if ((this._FValue1 != value))
				{
					this._FValue1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FValue2", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FValue2
		{
			get
			{
				return this._FValue2;
			}
			set
			{
				if ((this._FValue2 != value))
				{
					this._FValue2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FValue3", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FValue3
		{
			get
			{
				return this._FValue3;
			}
			set
			{
				if ((this._FValue3 != value))
				{
					this._FValue3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FReceiveString", DbType="VarChar(8000)")]
		public string FReceiveString
		{
			get
			{
				return this._FReceiveString;
			}
			set
			{
				if ((this._FReceiveString != value))
				{
					this._FReceiveString = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int FID
		{
			get
			{
				return this._FID;
			}
			set
			{
				if ((this._FID != value))
				{
					this._FID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCurrentStatus", DbType="VarChar(10)")]
		public string FCurrentStatus
		{
			get
			{
				return this._FCurrentStatus;
			}
			set
			{
				if ((this._FCurrentStatus != value))
				{
					this._FCurrentStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FProgramPhrase", DbType="VarChar(50)")]
		public string FProgramPhrase
		{
			get
			{
				return this._FProgramPhrase;
			}
			set
			{
				if ((this._FProgramPhrase != value))
				{
					this._FProgramPhrase = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FErrorNo", DbType="Int")]
		public System.Nullable<int> FErrorNo
		{
			get
			{
				return this._FErrorNo;
			}
			set
			{
				if ((this._FErrorNo != value))
				{
					this._FErrorNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FValue4", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FValue4
		{
			get
			{
				return this._FValue4;
			}
			set
			{
				if ((this._FValue4 != value))
				{
					this._FValue4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FValue5", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FValue5
		{
			get
			{
				return this._FValue5;
			}
			set
			{
				if ((this._FValue5 != value))
				{
					this._FValue5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FValue6", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> FValue6
		{
			get
			{
				return this._FValue6;
			}
			set
			{
				if ((this._FValue6 != value))
				{
					this._FValue6 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
